const OAUTH_CLIENT_ID = 2
const OAUTH_CLIENT_SECRECT = 'TLRJjBkoO84dWvAQ5cy8rIZZQTCzWTbvPe4qnW32'
const API_URL = 'http://appblog.192.168.2.102.nip.io/'
const LOGIN_URL = `${API_URL}oauth/token`
const SOCKET_SERVER =   'http://192.168.2.102:6001'
export { LOGIN_URL, API_URL, OAUTH_CLIENT_ID, OAUTH_CLIENT_SECRECT, SOCKET_SERVER }
